site_name: Tanzawa Documentation
theme: readthedocs
nav:
  - index.md
  - customization.md
  - 'Indieweb':
      - indieweb/relme.md
  - 'Plugins':
    - plugins/overview.md
    - plugins/custom-plugins.md
  - 'Theming':
      - themes/overview.md
  - 'Community':
    - sites-using-tanzawa.md
